# Generated by Django 3.0.6 on 2020-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.IntegerField(),
        ),
    ]
